# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cajón de sastre / cajón desastre.
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
baseurl: "/CDS"
url: "https://profesorjavi.github.io/CDS/"
permalink: /:day/:month/:year/:title
repository: profesorjavi/CDS
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/profesorjavi"
user: "Javier García"
user_email: "j.garciabenlloch@edu.gva.es"
contact_url: "https://portal.edu.gva.es/46017675/es/inici/"
google_tracking_id: "UA-96359860-1"
google_site_verification: "UA-96359860-1"
disqus_shortname: "profesorjavi"

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true